export const ERROR_CODES = {
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  EMAIL_NOT_PROVIDED: "EMAIL_NOT_PROVIDED",
  PASSWORD_NOT_PROVIDED: "PASSWORD_NOT_PROVIDED",
  JWT_SECRET_NOT_CONFIGURED: "JWT_SECRET_NOT_CONFIGURED",
  TOKEN_NOT_PROVIDED: "TOKEN_NOT_PROVIDED",
  INVALID_TOKEN: "INVALID_TOKEN",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  SERVER_ERROR: "SERVER_ERROR",
};